### PR TITLE
Fix #146 ArgumentOutOfRangeException in PagedWriterBuffer

### LINKED ISSUE #146: ArgumentOutOfRangeException in PagedWriterBuffer
I'm getting the following error:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: start
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at Amazon.IonDotnet.Internals.PagedWriterBuffer.WriteBytes(ReadOnlySpan`1 bytes)
   at Amazon.IonDotnet.Internals.PagedWriterBuffer.WriteUtf8(ReadOnlySpan`1 chars, Int32 length)
   at Amazon.IonDotnet.Internals.Binary.RawBinaryWriter.WriteString(String value)
```
In the constructor the `blockSize` gets set like this:
```
        protected PagedWriterBuffer(int intendedBlockSize)
        {
            ...
            this.currentBlock = ArrayPool<byte>.Shared.Rent(intendedBlockSize);
            ...
            this.blockSize = this.currentBlock.Length;
        }
```
Note that the `ArrayPool` can return a larger array than what you ask for.  Later on `currentBlock` gets replaced in `AllocateNewBlock`:
```
        private void AllocateNewBlock() {
            ...
            var newBlock = ArrayPool<byte>.Shared.Rent(this.blockSize);
            this.bufferBlocks.Add(newBlock);
            this.currentBlock = newBlock;
        }
```
What I'm running into is:
1.  The `blockSize` is set to 512 in the constructor and `currentBlock` starts out having length 512
2.  Later in `AllocateNewBlock` the `ArrayPool` returns a block that's 1024 and it's assigned to `currentBlock`
3.  The `WriteUtf8` method writes bytes as long as it doesn't go past `this.currentBlock.Length` which is 1024
4. The `WriteBytes` method looks at `blockSize` instead of `currentBlock.Length`:
```
        public void WriteBytes(ReadOnlySpan<byte> bytes)
        {
            ...
            var bytesToWrite = bytes.Length;
            while (bytesToWrite > 0)
            {
                // If blockSize is 512 and runningIndex is greater than 512 then "left" will be negative:
                var left = this.blockSize - this.runningIndex;  
                var bytesWritten = bytesToWrite > left ? left : bytesToWrite;
                // A negative number for bytesWritten causes the following to throw the ArgumentOutOfRangeException
                bytes.Slice(0, bytesWritten).CopyTo(new Span<byte>(this.currentBlock, this.runningIndex, bytesWritten));
                ...
            }
        }
```
I assume that `WriteBytes` should refer to `currentBlock.Length` like all the other methods do instead of `blockSize`.  Perhaps the `blockSize` field should be removed.  However, `AllocateNewBlock` needs to know what size to pass to `ArrayPool.Rent` so maybe the `intendedBlockSize` argument from the constructor should be stored in a readonly field for that purpose in place of using `blockSize`.

Thanks for making this library available!

### PR DESCRIPTION
**Pull request by CoderNate**
Replace `blockSize` field with `intendedBlockSize` and update `WriteBytes` to use `currentBlock.Length` in place of `blockSize`.  This  fixes the ArgumentOutOfRangeException described in the issue.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tgregg** [comment]
@CoderNate Thanks for the detailed report and the fix. It looks good to me. Would you be willing to add a short test that exercises the path that failed before the fix? That way we can be confident we won't inadvertently introduce a similar bug in the future.

**Comment by CoderNate** [comment]
I looked into writing a test but I don't know how to trigger .NET's `ArrayPool<>.Shared` to return an array larger than the minimum size you ask for.  I tried just renting and returning an array the next size up but it doesn't get used.  So I'm not sure how to trigger the failure in a test.

**Comment by CoderNate** [comment]
Hello, I posted in the original issue about a way to reproduce the problem on full framework but since it relies on the state of the globally static ArrayPool I don't know that there's a way to write a very good test.  Is there a chance of merging this without a unit test or is it useful to have a test that writes a bunch of random length strings?  Thanks!

**Review by tgregg — APPROVED** [review]

**Comment by tgregg** [comment]
@CoderNate Sorry for the delay, and thanks again for the fix. I'll merge it as-is and keep the related issue open so that we can revisit how to repeatably test this at some point in the future.

**Pull request merged**
